apiVersion: kafka.strimzi.io/v1beta2 
kind: Kafka 
metadata: 
  name: my-kafka-cluster 
spec: 
    kafka: 
      version: 2.8.0 
      replicas: 1 
      listeners: 
        - name: plain 
          port: 9092 
          type: internal 
          tls: false 
    zookeeper: 
      replicas: 1 
      storage: 
        type: ephemeral